### PR TITLE
Add C++ echo client and server with libdatachannel

### PR DESCRIPTION
**Pull request by paullouisageneau**
This PR adds C++ echo client and server with libdatachannel. The example import the libraries from submodules for now.

See https://github.com/sipsorcery/webrtc-echoes/issues/15

### CODE REVIEW

**Comment by sipsorcery** [comment]
Great to see this PR!

I've given the client and server apps a bit of a spin with mixed results. I only tested on Windows WSL though so there's a chance that's throwing a spanner in the works with openssl or libjuice. I saw some IPv6 warnings on some tests as well.

The server worked with the all the clients except mine :( (sipsorcery) which failed due to something going wrong with the STUN requests.

I had less luck with the client. I got DTLS errors with sipsorcery, pion and libwebrtc. With aiortc, gstreamer and kurento something went wrong with the HTTP offer/answer. With werift the error was "invalid remote port".

But that's the whole point of having these tests and I think it's well worth adding libdatachannel to the automated tests whenever you're ready. Once you merge the PR I can create the docker config and update the GitHub actions job.

**Comment by paullouisageneau** [comment]
> The server worked with the all the clients except mine :( (sipsorcery) which failed due to something going wrong with the STUN requests.

I'm sure it will be quickly, I'll look into it later!

> I had less luck with the client. I got DTLS errors with sipsorcery, pion and libwebrtc. 

This was caused by libdatachannel not negotiating SRTP as it should, it should be fixed by the libdatachannel update https://github.com/sipsorcery/webrtc-echoes/pull/28/commits/71de7c71ad3bb613d1cf7fcaf5ed3e52d468f864.

> With aiortc, gstreamer and kurento something went wrong with the HTTP offer/answer. > With werift the error was "invalid remote port".

I'll look into that too!

> But that's the whole point of having these tests and I think it's well worth adding libdatachannel to the automated tests whenever you're ready. Once you merge the PR I can create the docker config and update the GitHub actions job.

I was thinking about adding a Dockerfile myself before merging if you are fine with it.

**Comment by sipsorcery** [comment]
> I was thinking about adding a Dockerfile myself before merging if you are fine with it.

Sure, I'll leave it with you. Feel free to ping me if you run into any problems.

**Comment by paullouisageneau** [comment]
@sipsorcery There is an authentication issue when the libdatachannel container is pulled to be run as a client:
> docker: Error response from daemon: Head https://ghcr.io/v2/sipsorcery/libdatachannel-webrtc-echo/manifests/latest: unauthorized.

Do you know what I am missing here?

Also I'd like to thank you for your excellent work on the test matrix and this repo in general!

**Comment by sipsorcery** [comment]
GitHub publishes containers as private by default which is why you were unauthorized.

I've set the `libdatachannel` container as public [now](https://github.com/sipsorcery?tab=packages).

**Comment by paullouisageneau** [comment]
@sipsorcery OK thanks!

Looks good now, I'm merging.

**Pull request merged**
